import Head from "next/head";

import SocialIcons from "../../components/SocialIcons";

function ContactMe() {
  return (
    <section className="contact">
      <Head>
        <title>Contact Tiago</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Contact Me..</h2>

      <div className="contact__list">
        <div className="contact__email">
          <i className="fas fa-envelope"></i> Email
          <div className="text-secondary">tiagonec@outlook.com</div>
        </div>
      </div>

      <SocialIcons />
    </section>
  );
}

export default ContactMe;
