import Head from "next/head";

import Projects from "../../components/Projects";
import SocialIcons from "../../components/SocialIcons";

function MyProjects() {
  return (
    <div className="projects">
      <Head>
        <title>Tiago Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="projects__bio-image">
        <h1 className="text-secondary">My Projects</h1>
      </div>

      <Projects />

      <SocialIcons />
    </div>
  );
}

export default MyProjects;
