import Head from "next/head";

import Bio from "../../components/Bio";
import Jobs from "../../components/Jobs";
import SocialIcons from "../../components/SocialIcons";

function HomePage() {
  return (
    <div className="about">
      <Head>
        <title>About Tiago</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Bio />

      <Jobs />

      <SocialIcons />
    </div>
  );
}

export default HomePage;
