import Head from "next/head";

import SocialIcons from "../components/SocialIcons";

function HomePage() {
  return (
    <div className="home">
      <Head>
        <title>Tiago Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <section>
          <h2>Hi! My Name Is</h2>
          <h1 className="home__name">
            Tiago <span className="home__name--last">Caitano</span>
          </h1>
          <h2>Web Developer & Programmer</h2>
        </section>
      </>

      <SocialIcons />
    </div>
  );
}

export default HomePage;
